### This is the main way to configure the application (other than annotations).
### This fils is in Yaml format but you can also do this using the traditional
### Java properties file.

spring.jmx:
   enabled: false

spring.datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/DAS
    username: root
    password: root
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect



server:
  port: 8090

#todo: make sure to always enable security in production
security:
  basic:
    enabled: false

#management endpoints on a separate port
management:
  port: 8091
  security:
    enabled: false # management port is internal only. no need to secure it.

#default project info followed by actual injected pom-specified values.
project:
  name: yntaniq
  version: 0.1
  description: yntaniq - boot-example default description
info:
  build:
    artifact: ${project.artifactId}
    name: ${project.name}
    description: ${project.description}
    version: ${project.version}

yntaniq.service:
  name: 'default profile:'

spring.data.mongodb.database: DAS
spring.data.mongodb.uri: mongodb://192.168.0.47:27017

#spring.data.elasticsearch.cluster-nodes: localhost:9300
#spring.data.elasticsearch.properties.path.home: /Users/pelibossian/dev/elasticsearch-2.4.1

spring.mail.properties.mail.smtp.starttls.enable: true
spring.mail.host: smtp.gmail.com
spring.mail.username: pelibossian.test@gmail.com
spring.mail.password: norports1966
spring.mail.port: 587
spring.mail.smtp.auth: true

---
spring:
  profiles: test

spring.jpa:
    hibernate.ddl-auto: create-drop

hotel.service:
  name: 'test profile:'

